### PR TITLE
fix: routes generation script  + add usdzc swap routes

### PR DESCRIPTION
**Pull request by dohaki**
- Adds missing bridged USDC -> USDzC swap routes
- Refactors routes generation script for handling swap routes + bridged USDC routes

### CODE REVIEW

**Comment by gsteenkamp89** [comment]
Is it worthwhile writing tests for this script?

**Review by pxrl — APPROVED** [review]
The updated routes look good. Curious to see what you think RE @gsteenkamp89's question. Intuitively I think it seems tricky to test this automatically unless we end up  describing the routes separately, which is the purpose of this script anyway. wdyt - are there any options?

**Comment by dohaki** [comment]
> Is it worthwhile writing tests for this script?

@gsteenkamp89 I also thought about that. But as @pxrl already mentioned, I wouldn't know what values to "expect" in those tests 🤔 The only thing we could write tests for are regarding formatting of the output etc.

Maybe we could add something to compare routes to the ones configured on-chain? But this wouldn't cover swap routes for example

**Review by gsteenkamp89 — APPROVED** [review]
looks good!

**Pull request merged**
